# Generated by Django 5.1.2 on 2024-10-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("televent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventfindings",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ventfindings",
            name="type_of_breed",
            field=models.CharField(
                choices=[
                    ("Berkshire", "Berkshire"),
                    ("Duroc", "Duroc"),
                    ("Yorkshire", "Yorkshire"),
                    ("Landrace", "Landrace"),
                    ("Tamworth", "Tamworth"),
                    ("Large Black", "Large Black"),
                    ("Vietnamese Potbelly", "Vietnamese Potbelly"),
                    ("Juliana", "Juliana"),
                    ("Pietrain", "Pietrain"),
                    ("Chester White", "Chester White"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ventfindings",
            name="type_of_disease",
            field=models.CharField(
                choices=[
                    ("Swine Flu", "Swine Flu"),
                    ("African Swine Fever", "African Swine Fever"),
                    ("Porcine Reproductive and Respiratory Syndrome (PRRS)", "PRRS"),
                    ("Porcine Parvovirus", "Porcine Parvovirus"),
                    ("Leptospirosis", "Leptospirosis"),
                    ("Foot and Mouth Disease", "Foot and Mouth Disease"),
                    ("Transmissible Gastroenteritis", "Transmissible Gastroenteritis"),
                    (
                        "Actinobacillus pleuropneumonia",
                        "Actinobacillus pleuropneumonia",
                    ),
                    ("Erysipelas", "Erysipelas"),
                ],
                max_length=100,
            ),
        ),
    ]
