# Generated by Django 5.1.2 on 2024-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("televent", "0002_alter_ventfindings_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventfindings",
            name="symptoms",
            field=models.TextField(max_length=100),
        ),
    ]
