# Generated by Django 5.1.2 on 2024-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("televent", "0003_alter_ventfindings_symptoms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventfindings",
            name="age",
            field=models.CharField(
                choices=[("young", "Young"), ("medium", "Medium"), ("old", "Old")],
                max_length=100,
            ),
        ),
    ]
