# Generated by Django 5.1.2 on 2024-10-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("televent", "0004_alter_ventfindings_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ventfindings",
            name="date",
        ),
    ]
